### ISSUE TITLE
Assertj extension

### ISSUE THREAD

**Issue by aivinog1** [camunda-community-hub/bpmn-spec#142]
**Is your feature request related to a problem? Please describe.**
As a user, I will be very happy if I will have an `assertThat` method to test the result of ran spec. Right now I have to copy-paste like this:
```java
Assertions.assertThat(testResult.success)
                .describedAs("%s%nDetails: %s", testResult.message, testResult.output)
                .isTrue()
```

**Describe the solution you'd like**
This project has the `assertThat` method with fluent API.

**Describe alternatives you've considered**
Probably this should be created in a separate project.

**Comment by saig0** [comment]
@aivinog1 sounds interesting. Please descript your suggestion/solution in more detail. 

How should it look like? (i.e. code example)
How should it behave?

**Comment by aivinog1** [comment]
I'm thinking about something like this as a start:
```
val testResult = specRunner.runSingleTestCase(resources = spec.resources, testcase = spec.testCase)
assertThat(testResult).isSuccess()
```

In case of failure, it would be nice to print the whole test result (for me it is convenient to see that I have some incidents, to see some variables, etc.). We can control it with a verbose option for example 🤔
