### ISSUE TITLE
Can't see the 2.1.0 version in Maven Central

### ISSUE THREAD

**Issue by aivinog1** [camunda-community-hub/bpmn-spec#227]
**Describe the bug**
Hello! 
As I can see there is 2.1.0 release is out. But this version isn't available in Maven Central: https://central.sonatype.dev/artifact/io.zeebe.bpmn-spec/zeebe-test-runner/2.0.0/versions

**To Reproduce**
1. Go to the Maven Central
2. Try to find the 2.1.0 release

**Expected behavior**
I expect to found the 2.1.0 release

**Comment by saig0** [comment]
@aivinog1 good point. :+1: 

I forgot to release it from staging. :see_no_evil: 
It should be available tomorrow. :rocket:
